// Generated by CoffeeScript 1.3.3
(function() {
  var mongoose,
    __hasProp = {}.hasOwnProperty;

  mongoose = require('mongoose');

  exports.create = function() {
    var key, mongeese, value;
    mongeese = new mongoose.Mongoose();
    for (key in Mongoose) {
      if (!__hasProp.call(Mongoose, key)) continue;
      value = Mongoose[key];
      if (typeof mongoose[key] === 'undefined') {
        mongeese[key] = value;
      }
    }
    return mongeese;
  };

}).call(this);
